### ISSUE TITLE
Syntax error on commit  50983c5

### ISSUE THREAD

**Issue by croxis** [Half-Shot/matrix-appservice-twitter#67]
> /home/croxis/src/matrix-appservice-twitter/src/Provisioner.js:4

const log = util.logPrefix("Provisioner");
                                        ^
SyntaxError: Identifier 'log' has already been declared
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/croxis/src/matrix-appservice-twitter/twitter-as.js:12:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by Half-Shot** [comment]
Apologies, there was a bit of a disruption today where the develop branch was totally broken. Should be fixed now?

**Comment by croxis** [comment]
fixed!
