### ISSUE TITLE
Avatars are not being applied to users.

### ISSUE THREAD

**Issue by Half-Shot** [Half-Shot/matrix-appservice-twitter#69]
Logs:

```
2017-01-14 15:18:11.298 info Failed to send tweet. 
2017-01-14 15:18:11.298  - info: Failed to send tweet. 
2017-01-14 15:18:46.468 error UploadContent Failed to upload content:
Error: Unable to determine the domain name
2017-01-14 15:18:46.468  - error: UploadContent Failed to upload content:
Error: Unable to determine the domain name
2017-01-14 15:18:46.468 error Couldn't set new avatar for @%s because of %s kevtaur Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:25:13)
    at Object.exports.request (http.js:31:10)
    at Object.exports.get (http.js:35:21)
    at Promise (/srv/matrix/twitter-as/src/util.js:63:20)
    at Promise._execute (/srv/matrix/twitter-as/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.uploadContentFromUrl (/srv/matrix/twitter-as/src/util.js:60:10)
    at _storage.get_profile_by_id.then (/srv/matrix/twitter-as/src/twitter/Twitter.js:176:16)
    at tryCatcher (/srv/matrix/twitter-as/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:636:18)
    at Statement.<anonymous> (/srv/matrix/twitter-as/node_modules/bluebird/js/release/nodeback.js:42:21)
2017-01-14 15:18:46.468  - error: Couldn't set new avatar for @%s because of %s kevtaur Error: Unable to determine the domain name
    at new ClientRequest (_http_client.js:25:13)
    at Object.exports.request (http.js:31:10)
    at Object.exports.get (http.js:35:21)
    at Promise (/srv/matrix/twitter-as/src/util.js:63:20)
    at Promise._execute (/srv/matrix/twitter-as/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.uploadContentFromUrl (/srv/matrix/twitter-as/src/util.js:60:10)
    at _storage.get_profile_by_id.then (/srv/matrix/twitter-as/src/twitter/Twitter.js:176:16)
    at tryCatcher (/srv/matrix/twitter-as/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._settlePromise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:580:21)
    at Promise._settlePromise0 (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/srv/matrix/twitter-as/node_modules/bluebird/js/release/promise.js:636:18)
    at Statement.<anonymous> (/srv/matrix/twitter-as/node_modules/bluebird/js/release/nodeback.js:42:21)
2017-01-14 15:18:46.656 warn matrix-appservice-bridge [-] POST http://127.0.0.1:8444/_matrix/media/v1/upload (@_twitter_1094035068:half-shot.uk) HTTP 403 Error: "{\"errcode\":\"M_FORBIDDEN\",\"error\":\"Application service has not registered this user\"}"
2017-01-14 15:18:46.656  - warn: matrix-appservice-bridge [-] POST http://127.0.0.1:8444/_matrix/media/v1/upload (@_twitter_1094035068:half-shot.uk) HTTP 403 Error: "{\"errcode\":\"M_FORBIDDEN\",\"error\":\"Application service has not registered this user\"}"
2017-01-14 15:18:46.656 error UploadContent Failed to upload content:
M_FORBIDDEN: Application service has not registered this user
2017-01-14 15:18:46.656  - error: UploadContent Failed to upload content:
M_FORBIDDEN: Application service has not registered this user
2017-01-14 15:18:46.657 error Failed to submit tweet to queue, reason: %s { [M_FORBIDDEN: Application service has not registered this user]
  errcode: 'M_FORBIDDEN',
  name: 'M_FORBIDDEN',
  message: 'Application service has not registered this user',
  data: 
   { errcode: 'M_FORBIDDEN',
     error: 'Application service has not registered this user' },
  httpStatus: 403 }
2017-01-14 15:18:46.657  - error: Failed to submit tweet to queue, reason: %s { [M_FORBIDDEN: Application service has not registered this user]
  errcode: 'M_FORBIDDEN',
  name: 'M_FORBIDDEN',
  message: 'Application service has not registered this user',
  data: 
   { errcode: 'M_FORBIDDEN',
     error: 'Application service has not registered this user' },
  httpStatus: 403 }
```

**Comment by Half-Shot** [comment]
Fixed by #72
